### ISSUE TITLE
button menu position

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [vandread666/GhacksFiles#1]
default FF (64)
![button-menu-default](https://user-images.githubusercontent.com/16656956/51021396-53a41880-1579-11e9-99c6-169965fe9efd.png)

with userContent.css
![button-menu-css](https://user-images.githubusercontent.com/16656956/51021478-8b12c500-1579-11e9-9024-88a0bd7bfb13.png)

**Comment by vandread666** [comment]
Fixed!
